### ISSUE TITLE
Tracking Update

### ISSUE THREAD

**Issue by viorenparamitta** [KLYMM/cnergy-fe#273]
### Description
Terdapat beberapa revisi yang dibutuhkan untuk tracking Trstdly, seperti:
- [x] menampilkan hanya article/screen pada halaman homepage/index sesuai dengan jumlah kontennya
- [x] mengubah typo di virtual_sreenview menjadi virtual_screenview
- [x] menyamakan pagetitle pada GTM dengan title article /contentTitle
- [x] articleId bukan dr increment melainkan setiap artikel sudah memiliki id masing-masing
- [x] templateId diambil dari template 1-5 yang sudah ditentukan pada docs lampiran
- [x] menyesuaikan tracking pada readpage sesuai dengan story Data Tracking - Update
- [x] mengubah load satu page pada homepage dan index menjadi 25 article/25 screen
- [x] mengecek dan membetulkan bug pada value screen di virtual screen path

https://docs.google.com/document/d/1tIK5XjDfxs6VLjeCBuDpjEcLWfteJdY6l38LBpY78jU/edit?usp=sharing

**Comment by viorenparamitta** [comment]
Hal yang masih perlu diperbaiki:
1. templateId cukup menggunakan angka 1, 2, 3, 4, 5 seperti berikut
![Image](https://user-images.githubusercontent.com/90308302/207781542-441d8841-154b-4fde-9976-63b4d2bd924e.png)
